file:
  path: C:\\Users\\slapy\\OneDrive\\Dokumenty\\Projekty\\SprawdzKompletacje\\pliki\\
  finishedFilePath: finished\\

#server:
#  port : 8082
#
#spring:
#  devtools:
#    add-properties: true

#logging:
#  level:
#    web: DEBUG