spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://slawekdb.database.windows.net:1433;encrypt=true;trustServerCertificate=false;loginTimeout=30;database=KompletacjeDB;
    username: slawek84pl@slawekdb
    password: Sp32143435

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

admin:
  pass: password