file:
  path: C:\\Users\\slapy\\OneDrive\\Dokumenty\\Projekty\\SprawdzKompletacje\\pliki\\
  finishedFilePath: finished\\

spring:
  datasource:
    url: jdbc:h2:file:./data/kompletacje
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



#spring:
#  devtools:
#    add-properties: true

#logging:
#  level:
#    web: DEBUG